#!/bin/sh
./gameboy BROKER APPEARED_POKEMON Pikachu 9 9 100
./gameboy BROKER APPEARED_POKEMON Squirtle 6 7 101
./gameboy BROKER APPEARED_POKEMON Onix 2 8 102
./gameboy BROKER APPEARED_POKEMON Gengar 6 6 103
./gameboy BROKER APPEARED_POKEMON Squirtle 5 5 104
