#!/bin/sh
./gameboy BROKER CATCH_POKEMON Juan 1 2 

./gameboy BROKER NEW_POKEMON Otro 3 4 5

./gameboy BROKER GET_POKEMON Juancito

./gameboy SUSCRIPTOR CATCH_POKEMON 5
./gameboy SUSCRIPTOR GET_POKEMON 5

./gameboy BROKER CATCH_POKEMON Hola 6 7

./gameboy BROKER CAUGHT_POKEMON 102 OK
./gameboy BROKER CAUGHT_POKEMON 103 FAIL
./gameboy BROKER CAUGHT_POKEMON 104 OK

./gameboy SUSCRIPTOR CATCH_POKEMON 5
./gameboy SUSCRIPTOR CAUGHT_POKEMON 5

./gameboy BROKER GET_POKEMON PEPE

./gameboy BROKER CAUGHT_POKEMON 105 FAIL